src/controllers/BaseController.php
<?php
namespace yuankezhan\yiiExport\controllers;

class BaseController extends \yii\web\Controller
{

}

src/controllers/IndexController.php
<?php

namespace yuankezhan\yiiExport\controllers;

use yuankezhan\yiiExport\controls\FileOperate;
use yuankezhan\yiiExport\controls\FileOperation;
use yuankezhan\yiiExport\controls\Result;

class IndexController extends BaseController
{
    public $layout = 'main';

    public function actionIndex($methodUrl, $maxQuantity = 100, $startingPosition = 1, $name = "deriveIndex")
    {
        return $this->render('index', [
            "name" => $name,
            "maxQuantity" => $maxQuantity,
            "startingPosition" => $startingPosition,
            "methodUrl" => $methodUrl
        ]);
    }

    public function actionMethodDataOperate()
    {
        $jsonData = \Yii::$app->request->post("dataList", null);
        if (empty($jsonData)) {
            return json_encode(new Result(true, null, ""));
        }
        $obj = new FileOperation();
        $txtPathRes = $obj->writeTxt($jsonData);
        if (!$txtPathRes->Success) {
            return json_encode(new Result(false, null, $txtPathRes->Message));
        }
        return json_encode(new Result(true, $txtPathRes->Data, ""));
    }

    public function actionTriggerDownload()
    {
        $txtPathList = \Yii::$app->request->post("txtPathList", []);
        $startingPosition = \Yii::$app->request->post("startingPosition", 2);

        if (empty($txtPathList)) {
            return json_encode(new Result(false, [], "没有要写入的数据！"));
        }
        $obj = new FileOperation();
        $res = $obj->integrationExcel($txtPathList, $startingPosition);
        if (!$res->Success) {
            return json_encode(new Result(false, [], $res->Message));
        }
        return json_encode(new Result(true, $res->Data, ""));
    }

    public function actionDeleteExcelByHoldTime($holdTime)
    {
        $obj = new FileOperation();
        $res = $obj->deleteExcelFileByDate($holdTime);
        return json_encode($res);
    }

    public function actionDeleteTxtPath()
    {
        $txtPathList = \Yii::$app->request->post("txtPathList", []);
        FileOperate::delFiles($txtPathList);
        return json_encode(new Result(true, null, ""));
    }

}

src/views/index/index.php
<?php
use yii\helpers\Url;
?>

<div id="export-create-<?=$name?>"></div>

<script>
    var <?=$name?> = new Export ({
        dataOperate: '<?=Url::to(["index/method-data-operate"])?>',
        downloadUrl: '<?=Url::to(["index/trigger-download"])?>',
        deleteTxtUrl: '<?=Url::to(["index/delete-txt-path"])?>',
        deleteExcelUrl: '<?=Url::to(["index/delete-excel-by-hold-time"])?>',
        ele: '#export-create-<?=$name?>',
        methodUrl: '<?=$methodUrl?>',
        pageSize: <?=$maxQuantity?>,
        startingPosition: <?=$startingPosition?>
    });
</script>

src/views/layouts/main.php
<?php

use yuankezhan\yiiExport\Asset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

Asset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="none"/>
    <?= Html::csrfMetaTags() ?>
    <title>数据导出</title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>